openapi: 3.0.0
info:
  title: Notificator API
  description: API for sending notifications via email, Slack, and other services.
  version: 1.0.0
servers:
  - url: http://localhost:6200/api/v1
    description: Local server
  - url: https://notificator.bluejay.governify.io/api/v1
    description: Production server
paths:
  /notify/email:
    post:
      summary: Send an email notification
      description: Sends a notification via email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  oneOf:
                    - type: string
                      format: email
                      description: A single email address of the recipient.
                      example: user@example.com
                    - type: array
                      items:
                        type: string
                        format: email
                      description: An array of email addresses of the recipients.
                      example: ["user1@example.com", "user2@example.com"]
                subject:
                  type: string
                  description: The subject of the email.
                  example: "Welcome!"
                text:
                  type: string
                  description: The plain text content of the email.
                  example: "Hello, World!"
                html:
                  type: string
                  description: The HTML content of the email.
                  example: "Hello World! **Bold text**, _italic text_, `code`."
                isMarkdown:
                  type: boolean
                  description: Indicates if the `html` string is in Markdown format and the program should convert it to HTML.
                  example: true
      responses:
        '200':
          description: Email notification sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the operation was successful.
                    example: true
                  message:
                    type: string
                    description: A message describing the result.
                    example: "Email notification sent successfully."
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the operation was successful.
                    example: false
                  message:
                    type: string
                    description: A message describing the error.
                    example: "Invalid email address."
  /notify/slack:
    post:
      summary: Send a Slack notification
      description: Sends a notification via Slack.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slackWebhookUrl:
                  type: string
                  description: The Slack webhook URL.
                  example: https://hooks.slack.com/services/XXX/YYY/ZZZ
                message:
                  type: string
                  description: The markdown/text content of the Slack message.
                  example: "**Bold** _italic_ `code`"
      responses:
        '200':
          description: Slack notification sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the operation was successful.
                    example: true
                  message:
                    type: string
                    description: A message describing the result.
                    example: "Slack notification sent successfully."
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the operation was successful.
                    example: false
                  message:
                    type: string
                    description: A message describing the error.
                    example: "Invalid Slack webhook URL."
